services:
  frontend:
    build:
      context: ./containers/frontend
      dockerfile: dockerfile.develop
    env_file:
      - ./containers/frontend/env_file
    environment:
      - GID=${GID}
      - UID=${UID}
    ports:
      - 5173:5173
    volumes:
      - .:/work
