FROM node:20.9-bookworm

WORKDIR /work

RUN apt-get update && \
    apt-get install -y --no-install-recommends locales vim git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen ja_JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

COPY ./src/frontend /work

CMD [ "npx", "-y", "serve", "-s", "/work/dist", "-p", "80" ]
