FROM node:20.9-bookworm

WORKDIR /work/src/frontend

RUN apt-get update && \
    apt-get install -y --no-install-recommends locales vim git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen ja_JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

COPY ./docker-entrypoint-override.sh /usr/local/bin/docker-entrypoint-override.sh

RUN chmod +x /usr/local/bin/docker-entrypoint-override.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint-override.sh" ]

CMD [ "su", "node", "-c", "npm run dev" ]
